"""Export services: ICS calendar generation, lawyer brief, and markdown export."""
import datetime
import re

from app.models.schemas import DocumentAnalysisResponse, MissingStatusEnum, RiskLevelEnum


def parse_deadline_date(deadline_str: str | None) -> datetime.date:
    """Best-effort parser for contract deadline strings to produce calendar dates."""
    today = datetime.date.today()
    if not deadline_str:
        return today + datetime.timedelta(days=7)

    dl = deadline_str.lower()

    # Try month name parsing (e.g. October 1, 2024 or Sept 30, 2025)
    months = {
        "jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6,
        "jul": 7, "aug": 8, "sep": 9, "oct": 10, "nov": 11, "dec": 12
    }
    for m_prefix, m_num in months.items():
        if m_prefix in dl:
            # Look for day and year
            match = re.search(r"(\d{1,2})(?:st|nd|rd|th)?(?:,?\s*(\d{4}))?", dl)
            if match:
                day = int(match.group(1))
                year = int(match.group(2)) if match.group(2) else today.year
                try:
                    return datetime.date(year, m_num, min(day, 28))
                except ValueError:
                    pass

    # Relative days (e.g. within 14 days, within 60 days, within 7 days)
    days_match = re.search(r"(\d+)\s*(?:calendar\s*)?days?", dl)
    if days_match:
        days = int(days_match.group(1))
        return today + datetime.timedelta(days=days)

    # 1st of month
    if "1st" in dl or "first" in dl:
        # Next 1st of month
        next_month = today.month + 1 if today.month < 12 else 1
        year = today.year if today.month < 12 else today.year + 1
        return datetime.date(year, next_month, 1)

    # Default to 14 days from now
    return today + datetime.timedelta(days=14)


def generate_ics_calendar(analysis: DocumentAnalysisResponse) -> str:
    """Generate RFC 5545 compliant iCalendar (.ics) string for obligations & deadlines."""
    now_utc = datetime.datetime.now(datetime.UTC).strftime("%Y%m%dT%H%M%SZ")
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//ClauseCompass//Legal Obligation Calendar//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        f"X-WR-CALNAME:ClauseCompass Deadlines ({analysis.doc_type.title()})",
    ]

    event_idx = 1
    for clause in analysis.clauses:
        for ob in clause.obligations:
            event_date = parse_deadline_date(ob.deadline)
            dt_str = event_date.strftime("%Y%m%d")
            dt_end_str = (event_date + datetime.timedelta(days=1)).strftime("%Y%m%d")
            uid = f"clausecompass-{analysis.doc_id[:8]}-{event_idx}@{analysis.doc_type}"

            summary = f"[{clause.category}] {ob.who}: {ob.what[:60]}"
            description = (
                f"Obligation: {ob.what}\\n"
                f"Responsible Party: {ob.who}\\n"
                f"Contract Deadline: {ob.deadline or 'As specified in contract'}\\n"
                f"Clause: {clause.title}\\n"
                f"Risk Level: {clause.risk_level.value.upper()}\\n"
                f"Action Note: {clause.actionable_recommendation or 'Review agreement'}\\n\\n"
                f"-- Generated by ClauseCompass (Information, not legal advice)"
            )

            lines.extend([
                "BEGIN:VEVENT",
                f"UID:{uid}",
                f"DTSTAMP:{now_utc}",
                f"DTSTART;VALUE=DATE:{dt_str}",
                f"DTEND;VALUE=DATE:{dt_end_str}",
                f"SUMMARY:{summary}",
                f"DESCRIPTION:{description}",
                "BEGIN:VALARM",
                "TRIGGER:-P1D",
                "ACTION:DISPLAY",
                f"DESCRIPTION:Reminder: {summary}",
                "END:VALARM",
                "END:VEVENT",
            ])
            event_idx += 1

    lines.append("END:VCALENDAR")
    return "\r\n".join(lines) + "\r\n"


def generate_lawyer_brief(analysis: DocumentAnalysisResponse) -> str:
    """Generate a structured 'Questions for your lawyer' brief in Markdown."""
    lines = [
        "# Legal Review Brief: Questions for Your Lawyer / Counterparty",
        f"**Document Type**: {analysis.doc_type.title()} | **User Role**: {analysis.role.title()}",
        f"**Verification Score**: {analysis.verification_score}% | **Risk Summary**: {analysis.high_risk_count} High, {analysis.medium_risk_count} Medium, {analysis.low_risk_count} Low",
        "\n> **DISCLAIMER**: This document contains legal information for review purposes and does NOT constitute legal advice.\n",
        "## 1. High-Risk Items Requiring Clarification or Amendment",
    ]

    high_risks = [c for c in analysis.clauses if c.risk_level == RiskLevelEnum.HIGH]
    if not high_risks:
        lines.append("_No critical high-risk clauses were flagged._\n")
    else:
        for idx, c in enumerate(high_risks, start=1):
            lines.append(f"### {idx}. {c.title} ({c.category})")
            lines.append(f"- **Summary**: {c.plain_language_summary}")
            lines.append(f"- **Why it's High Risk**: {c.risk_reason}")
            lines.append(f"- **Role Impact**: {c.user_role_impact}")
            if c.evidence:
                lines.append(f"- **Document Citation ({c.evidence[0].paragraph_id})**: *\"{c.evidence[0].exact_quote}\"*")
            if c.actionable_recommendation:
                lines.append(f"- **Suggested Question / Negotiation Ask**: **{c.actionable_recommendation}**")
            lines.append("")

    lines.append("## 2. Missing Standard Clauses to Request")
    missing = [m for m in analysis.missing_clauses if m.status == MissingStatusEnum.NOT_FOUND]
    if not missing:
        lines.append("_All standard clauses for this contract type were detected._\n")
    else:
        for idx, m in enumerate(missing, start=1):
            lines.append(f"### {idx}. Missing: {m.clause_name}")
            lines.append(f"- **Why It Matters**: {m.why_it_matters}")
            lines.append(f"- **Question to Ask**: *\"{m.question_to_ask}\"*")
            lines.append("")

    lines.append("## 3. Extracted Deadlines & Actionable Obligations")
    has_obs = False
    for c in analysis.clauses:
        for ob in c.obligations:
            has_obs = True
            lines.append(f"- **[{ob.who}]** {ob.what} *(Deadline: {ob.deadline or 'Unspecified'})* — from {c.title}")
    if not has_obs:
        lines.append("_No explicit chronological deadlines detected._")

    return "\n".join(lines)


def generate_markdown_export(analysis: DocumentAnalysisResponse) -> str:
    """Generate complete markdown export of the analyzed document."""
    lines = [
        f"# ClauseCompass Analysis Report: {analysis.doc_type.title()} Agreement",
        f"- **Analyzed For Role**: {analysis.role.title()}",
        f"- **Reading Level**: {analysis.reading_level.title()} | **Language**: {analysis.language.upper()}",
        f"- **Deterministic Verification Score**: {analysis.verification_score}%",
        f"- **Risk Profile**: {analysis.high_risk_count} High | {analysis.medium_risk_count} Medium | {analysis.low_risk_count} Low",
        f"- **Paragraphs Analyzed**: {analysis.total_paragraphs}",
        "\n> **Notice**: ClauseCompass provides legal information, not legal advice.\n",
        "## Clause-by-Clause Breakdown\n",
    ]

    for c in analysis.clauses:
        risk_emoji = "🔴 HIGH RISK" if c.risk_level == RiskLevelEnum.HIGH else ("🟡 MEDIUM RISK" if c.risk_level == RiskLevelEnum.MEDIUM else "🟢 LOW RISK")
        lines.append(f"### {c.title} — {risk_emoji}")
        lines.append(f"**Category**: {c.category}\n")
        lines.append(f"**Plain-Language Summary**: {c.plain_language_summary}\n")
        lines.append(f"**Risk Evaluation**: {c.risk_reason}\n")
        lines.append(f"**Impact on {analysis.role.title()}**: {c.user_role_impact}\n")

        if c.evidence:
            lines.append("**Grounded Evidence Citations**:")
            for ev in c.evidence:
                st = "✓ VERIFIED" if ev.verification_status.value == "VERIFIED" else f"⚠️ {ev.verification_status.value}"
                lines.append(f"- `[{ev.paragraph_id}]` *\"{ev.exact_quote}\"* — **{st}**")
            lines.append("")

        if c.obligations:
            lines.append("**Extracted Obligations**:")
            for ob in c.obligations:
                lines.append(f"- **{ob.who}**: {ob.what} (Due: {ob.deadline or 'N/A'})")
            lines.append("")

        if c.actionable_recommendation:
            lines.append(f"**Recommendation**: {c.actionable_recommendation}\n")
        lines.append("---\n")

    return "\n".join(lines)
